### ISSUE TITLE
MNIST data corrupted

### ISSUE THREAD

**Issue by dsitnik** [kowshikthopalli/deep_subspace_clustering_networks#2]
Is The MNIST dataset corrupted? I tried different libraries and I couldn't open it. 

> OSError: Failed to interpret file './Data/mnist_256.npz' as a pickle

**Comment by kowshikthopalli** [comment]
Hi
I just verified that the file can be opened by these lines. I am unable to reproduce the error https://github.com/kowshikthopalli/deep_subspace_clustering_networks/blob/5f351ef75526691b0eab917a0e9502adbec91aee/DSC-Net-L2-MNIST.py#L320

**Comment by dsitnik** [comment]
What numpy version are you using?

**Comment by kowshikthopalli** [comment]
1.16.4

**Comment by dsitnik** [comment]
Works now! Thank you!
